modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0 License"
issueTrackerURL="https://github.com/AeronicaMC/mxTune/issues"

[[mods]]
    modId="mxtune"
    version="${version}"
    displayName="mxTune"
    updateJSONURL="https://gist.githubusercontent.com/Aeronica/dbc2619e0011d5bdbe7a162d0c6aa82b/raw/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mxtune"
    logoFile="mxtune.png"
    credits="The Forge and FML guys, TheGreyGhost, coolAlias, Choonster,  diesieben07, McJty, OreCruncher, MrCrayFish, BedrockMiner, The Modding Community"
    authors="Aeronica"
    description='''MML Music for all occasions'''

[[dependencies.mxtune]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mxtune]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"