@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package aeronicamc.mods.mxtune.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;