//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.06 at 08:58:51 AM CST 
//


package net.aeronica.libs.mml.readers.ms2mml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.aeronica.libs.mml.readers.ms2mml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.aeronica.libs.mml.readers.ms2mml
     * 
     */
    public ObjectFactory() { /* NOP */
    }

    /**
     * Create an instance of {@link Ms2 }
     * 
     */
    public Ms2 createMs2() {
        return new Ms2();
    }

    /**
     * Create an instance of {@link Ms2.Chord }
     * 
     */
    public Ms2.Chord createMs2Chord() {
        return new Ms2.Chord();
    }

}
